name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          config_path: zmk-firmware/build.yaml
